name: mainBuild

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3

      - name: install
        run: npm install

      - name: lint
        run: make lint
      
      - name: run tests
        run: npm test
